### ISSUE TITLE
Moving faster than elevator..!?

### ISSUE THREAD

**Issue by Fabse101** [Pecacheu/Elevators-v2#15]
Hi, I'm using an old version of Minecraft (1.8.9, because it's nostalgia and my friends and I like it...) And I Installed the Plugin serveral times on other servers with newer versions. And it all worked fine! I really love this plugin.
But when I'm using an elevator in MC 1.8.9, (w/ plugin _version 2.8.9 (1.7.10 edition_)) I move faster than the elevator itself... It's bit buggy and it doesn't look healthy... :,D

What I'm asking for: Is there any version of this Plugin, that is fully funktionable in 1.8.9? 

And I'm sorry for my bad english, I'm from Germany... best greetings :3

**Comment by Pecacheu** [comment]
That's odd, in newer versions it feels like players are moving a bit too slow rather than too fast. I don't know if I have the bandwidth to make versions for old game versions when I have so many projects to work on though, sadly :/

I do recall what was previously the latest version (3.2.0) working fine in a 1.7.10 modded server though.
