### ISSUE TITLE
Not functional with the latest Paper

### ISSUE THREAD

**Issue by OverDhill** [Pecacheu/Elevators-v2#20]
Call button does nothing.

**Comment by RichDAudio** [comment]
Elevators become invalid on Paper 1.16.5 Build 507 https://github.com/PaperMC/Paper/pull/5289, You can create an elevator but becomes invalid and unusable. 
[latest.log](https://github.com/Pecacheu/Elevators-v2/files/6095800/latest.log)

**Comment by Pecacheu** [comment]
Hiya. Sorry for taking *SOOOO* long to get back to this project but I was finally motivated to, someone updated it to 1.16 for me and gave me the code a lil while ago. And just now I've updated it and tested on the latest 1.18.1 Paper (everyone seems to be using paper these days so I'm testing on that instead of Spigot now)

Will be posting JAR builds soon. Though there is a config file saving bug that seems to have been introduced so I'll have to address that.

**Comment by Pecacheu** [comment]
Latest version is now published
